# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-21 05:49
from __future__ import unicode_literals

import UniversalKLAuthUser.managers
from django.db import migrations, models
import guardian.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKL',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255, null=True)),
                ('UserIDKL', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('LKD', models.CharField(default='', max_length=255, null=True)),
                ('FB', models.IntegerField(default=0, null=True)),
                ('GPlus', models.IntegerField(default=0, null=True)),
                ('KL', models.IntegerField(default=0, null=True)),
                ('LearnNet', models.IntegerField(default=0, null=True)),
                ('BookNet', models.IntegerField(default=0, null=True)),
                ('SigMa', models.IntegerField(default=0, null=True)),
                ('Pi', models.IntegerField(default=0, null=True)),
                ('CurrentRefferalID', models.CharField(default='KarmaaLab', max_length=255)),
                ('PreviousRefferalID', models.CharField(default='KarmaaLab', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('ModifiedOn', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'UserKL',
            },
            bases=(guardian.mixins.GuardianUserMixin, models.Model),
            managers=[
                ('objects', UniversalKLAuthUser.managers.UserKLManager()),
            ],
        ),
    ]
